### ISSUE TITLE
500 error on mark complete

### ISSUE THREAD

**Issue by benwbrum** [CivilWarGovernorsOfKentucky/Mashbill#109]
reproduce on document:  KYR-0001-005-0074

I, [2018-04-10T11:30:13.404148 #10654]  INFO -- : Started GET "/documents/search?utf8=%E2%9C%93&q=KYR-0001-005-0074&commit=Search" for 70.112.51.219 at 2018-04-10 11:30:13 -0400
I, [2018-04-10T11:30:13.405980 #10654]  INFO -- : Processing by DocumentsController#search as HTML
I, [2018-04-10T11:30:13.406066 #10654]  INFO -- :   Parameters: {"utf8"=>"✓", "q"=>"KYR-0001-005-0074", "commit"=>"Search"}
I, [2018-04-10T11:30:13.425598 #10654]  INFO -- :   Rendered documents/search.erb within layouts/application (16.0ms)
I, [2018-04-10T11:30:13.427384 #10654]  INFO -- : Completed 200 OK in 21ms (Views: 3.5ms | ActiveRecord: 15.1ms)
I, [2018-04-10T11:30:16.003549 #10654]  INFO -- : Started GET "/annotations/document/KYR-0001-005-0074" for 70.112.51.219 at 2018-04-10 11:30:16 -0400
I, [2018-04-10T11:30:16.004957 #10654]  INFO -- : Processing by AnnotationsController#bycwgkid as HTML
I, [2018-04-10T11:30:16.005022 #10654]  INFO -- :   Parameters: {"cwgk_id"=>"KYR-0001-005-0074"}
I, [2018-04-10T11:30:16.035711 #10654]  INFO -- :   Rendered deeds/_deed.html.erb (1.4ms)
I, [2018-04-10T11:30:16.036820 #10654]  INFO -- :   Rendered deeds/_deed.html.erb (0.7ms)
I, [2018-04-10T11:30:16.038202 #10654]  INFO -- :   Rendered deeds/_deed.html.erb (1.0ms)
I, [2018-04-10T11:30:16.039554 #10654]  INFO -- :   Rendered deeds/_deed.html.erb (1.0ms)
I, [2018-04-10T11:30:16.040637 #10654]  INFO -- :   Rendered deeds/_deed.html.erb (0.7ms)
I, [2018-04-10T11:30:16.041704 #10654]  INFO -- :   Rendered deeds/_deed.html.erb (0.7ms)
I, [2018-04-10T11:30:16.042746 #10654]  INFO -- :   Rendered deeds/_deed.html.erb (0.7ms)
I, [2018-04-10T11:30:16.043822 #10654]  INFO -- :   Rendered deeds/_deed.html.erb (0.8ms)
I, [2018-04-10T11:30:16.044840 #10654]  INFO -- :   Rendered deeds/_deed.html.erb (0.7ms)
I, [2018-04-10T11:30:16.045880 #10654]  INFO -- :   Rendered deeds/_deed.html.erb (0.7ms)
I, [2018-04-10T11:30:16.049070 #10654]  INFO -- :   Rendered deeds/_deed.html.erb (2.8ms)
I, [2018-04-10T11:30:16.052207 #10654]  INFO -- :   Rendered deeds/_deed.html.erb (2.8ms)
I, [2018-04-10T11:30:16.055260 #10654]  INFO -- :   Rendered deeds/_deed.html.erb (2.7ms)
I, [2018-04-10T11:30:16.058343 #10654]  INFO -- :   Rendered deeds/_deed.html.erb (2.8ms)
I, [2018-04-10T11:30:16.061366 #10654]  INFO -- :   Rendered deeds/_deed.html.erb (2.7ms)
I, [2018-04-10T11:30:16.064389 #10654]  INFO -- :   Rendered deeds/_deed.html.erb (2.7ms)
I, [2018-04-10T11:30:16.067604 #10654]  INFO -- :   Rendered deeds/_deed.html.erb (2.8ms)
I, [2018-04-10T11:30:16.070684 #10654]  INFO -- :   Rendered deeds/_deed.html.erb (2.7ms)
I, [2018-04-10T11:30:16.071860 #10654]  INFO -- :   Rendered deeds/_deed.html.erb (0.8ms)
I, [2018-04-10T11:30:16.073228 #10654]  INFO -- :   Rendered deeds/_deed.html.erb (1.0ms)
I, [2018-04-10T11:30:16.076188 #10654]  INFO -- :   Rendered deeds/_deed.html.erb (2.6ms)
I, [2018-04-10T11:30:16.079246 #10654]  INFO -- :   Rendered deeds/_deed.html.erb (2.7ms)
I, [2018-04-10T11:30:16.082450 #10654]  INFO -- :   Rendered deeds/_deed.html.erb (2.9ms)
I, [2018-04-10T11:30:16.085599 #10654]  INFO -- :   Rendered deeds/_deed.html.erb (2.8ms)
I, [2018-04-10T11:30:16.088734 #10654]  INFO -- :   Rendered deeds/_deed.html.erb (2.8ms)
I, [2018-04-10T11:30:16.091782 #10654]  INFO -- :   Rendered deeds/_deed.html.erb (2.7ms)
I, [2018-04-10T11:30:16.094805 #10654]  INFO -- :   Rendered deeds/_deed.html.erb (2.7ms)
I, [2018-04-10T11:30:16.097996 #10654]  INFO -- :   Rendered deeds/_deed.html.erb (2.9ms)
I, [2018-04-10T11:30:16.101290 #10654]  INFO -- :   Rendered deeds/_deed.html.erb (2.9ms)
I, [2018-04-10T11:30:16.104392 #10654]  INFO -- :   Rendered deeds/_deed.html.erb (2.8ms)
I, [2018-04-10T11:30:16.104488 #10654]  INFO -- :   Rendered deeds/_deeds.html.erb (72.9ms)
I, [2018-04-10T11:30:16.104611 #10654]  INFO -- :   Rendered annotations/index.html.erb within layouts/application (95.5ms)
I, [2018-04-10T11:30:16.105719 #10654]  INFO -- : Completed 200 OK in 101ms (Views: 87.1ms | ActiveRecord: 10.4ms)
I, [2018-04-10T11:30:22.679783 #10654]  INFO -- : Started POST "/documents/mark_complete/805" for 70.112.51.219 at 2018-04-10 11:30:22 -0400
I, [2018-04-10T11:30:22.681223 #10654]  INFO -- : Processing by DocumentsController#mark_complete as HTML
I, [2018-04-10T11:30:22.681292 #10654]  INFO -- :   Parameters: {"authenticity_token"=>"5bfkHjdw+Exg8KMfdIbon6C1idV2Zjs82+CE1AzCIbzfWxM3tVp8CIc9xoyh91rLM2uS+ffsMUWoNjailIkG5Q==", "id"=>"805"}
I, [2018-04-10T11:30:23.842396 #10654]  INFO -- : Completed 500 Internal Server Error in 1161ms (ActiveRecord: 6.0ms)
F, [2018-04-10T11:30:23.843389 #10654] FATAL -- :
NoMethodError (undefined method `captures' for nil:NilClass
Did you mean?  capture):
  lib/tei_annotator.rb:142:in `target_element_and_index'
  lib/tei_annotator.rb:136:in `target_element'
  lib/tei_annotator.rb:69:in `apply_annotation'
  lib/tei_annotator.rb:14:in `block in apply_annotations'
  lib/tei_annotator.rb:13:in `apply_annotations'
  app/controllers/documents_controller.rb:129:in `update_tei'
  app/controllers/documents_controller.rb:71:in `mark_complete'

A git status on the server shows it's up to date.  a git pull shows no additions.

**Comment by benwbrum** [comment]
We've tried to reproduce this in controlled environments several times, and will just need to add more logging to the code, deploy that in production, and watch that in order to make progress on this.
