### ISSUE TITLE
Mashbill assumes annotations are always of paragraphs

### ISSUE THREAD

**Issue by benwbrum** [CivilWarGovernorsOfKentucky/Mashbill#87]
For KYR-0362-001-0001, paragraphs in the [TEI on Github](https://github.com/CivilWarGovernorsOfKentucky/TestDocuments/blob/master/document_xml/KYR-0362-001-0001.xml) now are presented as `div`/`h3` pairs at [KYR-0362-001-0001 on Omeka](http://discovery.civilwargovernors.org/document/KYR-0362-001-0001).

This shows up in a problem updating documents through Mashbill, so I'm wondering whether this is a recent change to address the columns-of-signatures problem or something already present which I missed.

**Comment by benwbrum** [comment]
Here are the three problematic annotations on this document:

```ruby
{"id"=>619,
 "document_id"=>80,
 "verbatim"=>"General Assembly of Kentucky",
 "user_id"=>1,
 "entity_id"=>923,
 "hypothesis_date"=>Tue, 10 Jan 2017,
 "hypothesis_annotation_id"=>"UauS2NdLEeaf2W9t2zDZbw",
 "hypothesis_user"=>"KyPLewis@hypothes.is",
 "created_at"=>Tue, 10 Jan 2017 15:51:17 UTC +00:00,
 "updated_at"=>Tue, 28 Mar 2017 15:15:08 UTC +00:00,
 "prefix"=>"rnor, Heads of Departments, and ",
 "suffix"=>", will be pleased to see you at ",
 "start_container"=>
  "/div[1]/div[2]/aside[1]/div[1]/tei[1]/div[1]/text[1]/p[3]"}
{"id"=>618,
 "document_id"=>80,
 "verbatim"=>"CAPITAL HOTEL",
 "user_id"=>1,
 "entity_id"=>203,
 "hypothesis_date"=>Tue, 10 Jan 2017,
 "hypothesis_annotation_id"=>"VxxI6NdLEeaf2p-Yti8DQw",
 "hypothesis_user"=>"KyPLewis@hypothes.is",
 "created_at"=>Tue, 10 Jan 2017 15:51:17 UTC +00:00,
 "updated_at"=>Tue, 10 Jan 2017 15:52:11 UTC +00:00,
 "prefix"=>"ll be pleased to see you at the ",
 "suffix"=>", FRANKFORT, KENTUCKY, Tuesday E",
 "start_container"=>
  "/div[1]/div[2]/aside[1]/div[1]/tei[1]/div[1]/text[1]/p[3]"}
{"id"=>617,
 "document_id"=>80,
 "verbatim"=>"FRANKFORT, KENTUCKY",
 "user_id"=>1,
 "entity_id"=>24,
 "hypothesis_date"=>Tue, 10 Jan 2017,
 "hypothesis_annotation_id"=>"WkgvvtdLEeaU__9_z3SP5g",
 "hypothesis_user"=>"KyPLewis@hypothes.is",
 "created_at"=>Tue, 10 Jan 2017 15:51:17 UTC +00:00,
 "updated_at"=>Tue, 10 Jan 2017 15:52:20 UTC +00:00,
 "prefix"=>"o see you at the CAPITAL HOTEL, ",
 "suffix"=>", Tuesday Evening, Feb. 24, at 8",
 "start_container"=>
  "/div[1]/div[2]/aside[1]/div[1]/tei[1]/div[1]/text[1]/p[3]"}
```

**Comment by saracarl** [comment]
FRANKFORT, KENTUCKY is in the dom path here:
div
div
aside
div
tei
div
text
p
(text is here)

**Comment by benwbrum** [comment]
Further research reveals that Hypothesis and Omeka are all behaving correctly.   The challenge is that Mashbill's `TeiAnnotator` is written on an invalid assumption: that all text occurs within paragraphs.

This manifests itself by throwing an error when this document is saved and the system attempts to locate a paragraph for an annotation with a non-paragraph locator

```
Completed 500 Internal Server Error in 1675ms (ActiveRecord: 11.9ms)

NoMethodError (undefined method `captures' for nil:NilClass
Did you mean?  capture):
  lib/tei_annotator.rb:77:in `target_paragraph_number'
  lib/tei_annotator.rb:71:in `target_paragraph'
  lib/tei_annotator.rb:31:in `apply_annotation'
  lib/tei_annotator.rb:14:in `block in apply_annotations'
  lib/tei_annotator.rb:13:in `apply_annotations'
  app/controllers/documents_controller.rb:129:in `update_tei'
  app/controllers/documents_controller.rb:71:in `mark_complete'
```
